=== shithead/textmining/elearningtextmining.dtd
<!ELEMENT a ( #PCDATA ) >
<!ATTLIST a href CDATA #REQUIRED >

<!ELEMENT author ( #PCDATA ) >

<!ELEMENT authors ( author+ ) >

<!ELEMENT bib ( #PCDATA | person )* >
<!ATTLIST bib id NMTOKEN #REQUIRED >

<!ELEMENT chapter ( meta | page )* >
<!ATTLIST chapter id NMTOKEN #REQUIRED >

<!ELEMENT date ( #PCDATA ) >

<!ELEMENT emph ( #PCDATA ) >

<!ELEMENT h1 ( #PCDATA ) >

<!ELEMENT h2 ( #PCDATA ) >

<!ELEMENT img EMPTY >
<!ATTLIST img src CDATA #REQUIRED >

<!ELEMENT learningObjective ( h1 | p | ul )* >

<!ELEMENT li ( #PCDATA | emph | a | bib | img | person | term )* >

<!ELEMENT meta ( title, version, date, authors ) >

<!ELEMENT module ( meta, chapter+ ) >

<!ELEMENT p ( #PCDATA | a | bib | emph | img | person | term )* >
<!ATTLIST p type NMTOKEN #IMPLIED >

<!ELEMENT page ( h1 | h2 | learningObjective | p | ul )* >

<!ELEMENT person ( #PCDATA ) >
<!ATTLIST person name CDATA #REQUIRED >

<!ELEMENT term ( #PCDATA ) >

<!ELEMENT title ( #PCDATA ) >

<!ELEMENT ul ( li+ ) >

<!ELEMENT version ( #PCDATA ) >

=== shithead/textmining/demoInhalt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "elearningtextmining.dtd">
<module>
	<meta>
		<title>e-Learning-Kurs</title>
		<version>1.0</version>
		<date>2014-05-01</date>
		<authors>
			<author>Yvonne Krämer</author>
			<author>N. N.</author>
		</authors>
	</meta>
	<chapter id="1">
		<meta>
			<title>Kollokationen</title>
			<version>1.0</version>
			<date>2014-05-01</date>
			<authors>
				<author>Yvonne Krämer</author>
			</authors>
		</meta>
		<page>
			<learningObjective>
				<h1>Lernziele des Moduls "Kollokationen"</h1>
				<p>Nach Bearbeitung des Moduls</p>
				<ul>
					<li>können Sie erklären, was Kollokationen sind.</li>
					<li>sind Sie sich der terminologischen Problematik des Begriffs bewusst.</li>
				</ul>
			</learningObjective>
		</page>
		<page>
			<h1>Einführung</h1>
			<h2>Was ist eine Kollokation?</h2>
			<p>Der Begriff <term>Kollokation</term> geht auf <person name="Firth, John Rupert">J. R. Firth</person> (<bib id="Firth1957">1957</bib>) zurück, der damit charakteristische und <emph>häufig wiederkehrende Wortkombinationen</emph> bezeichnete.</p>
			<p type="note">Ein Kollokator ist ein Element...</p>
			<p><emph>Vielzitiert</emph> ist in diesem Zusammenhang der Satz <person name="Firth, John Rupert">Firths</person>
"You shall know a word by the company it keeps" (<bib id="Firth1957"><person name="Firth, John Rupert">Firth</person> 1957</bib>, in <bib id="Evert2009:1213"><person name="Evert, Stefan">Evert</person> 2009: 1213</bib>).</p> 
			<h2>Noch ein Titel</h2>
			<p></p>
			<h1>Ein Titel</h1>
			<p></p>
			<p type="quote">Ein Blockzitat...</p>
			<p><a href="http://linguistik.zih.tu-dresden.de">Ein Link</a>.</p>
			<p><img src="http://linguistik.zih.tu-dresden.de/LogoDCDL160.png"/></p>
		</page>
	</chapter>
	<chapter id="2">
		<page>
			<h1>Ein Titel</h1>
			<p></p>
			<p type="quote">Ein Blockzitat...</p>
		</page>
	</chapter>
</module>
